INSERT INTO paye (code, label) VALUES
('DZ', 'Algérie'),
('FR', 'France'),
('TN', 'Tunisie'),
('MA', 'Maroc'),
('ES', 'Espagne'),
('IT', 'Italie'),
('DE', 'Allemagne'),
('TR', 'Turquie'),
('CN', 'Chine'),
('UK', 'Royaume-Uni'),
('US', 'États-Unis'),
('AE', 'Émirats Arabes Unis'),
('SA', 'Arabie Saoudite'),
('PT', 'Portugal'),
('BE', 'Belgique'),
('CH', 'Suisse'),
('CA', 'Canada'),
('RU', 'Russie'),
('JP', 'Japon'),
('NL', 'Pays-Bas');